export const ABOUT_INQUIRY_POST_REQUEST = 'ABOUT_INQUIRY_POST_REQUEST';
export const ABOUT_INQUIRY_POST_SUCCESS = 'ABOUT_INQUIRY_POST_SUCCESS';
export const ABOUT_INQUIRY_POST_FAILURE = 'ABOUT_INQUIRY_POST_FAILURE';

export const ABOUT_SET_CURRENT_DATE = 'ABOUT_SET_CURRENT_DATE';
export const ABOUT_SET_CURRENT_TIME = 'ABOUT_SET_CURRENT_TIME';

export const SET_BAKERY_FROM_BAKE_DETAILS = 'SET_BAKERY_FROM_BAKE_DETAILS';
export const REMOVE_BAKERY_FROM_BAKE_DETAILS = 'REMOVE_BAKERY_FROM_BAKE_DETAILS';
