export const STUFF = 'STUFF';

export const REQUEST = 'ADMIN_BULK_UPLOAD_REQUEST';
export const SUCCESS = 'ADMIN_BULK_UPLOAD_SUCCESS';
export const FAILURE = 'ADMIN_BULK_UPLOAD_FAILURE';

export const IMAGES_FROM_LOCAL_STORAGE = 'IMAGES_FROM_LOCAL_STORAGE';
export const IMAGES_TO_LOCAL_STORAGE = 'IMAGES_TO_LOCAL_STORAGE';
export const SET_CURRENT_FILE_TO_CROP = 'SET_CURRENT_FILE_TO_CROP';
export const REMOVE_IMAGES_FROM_LOCAL_STORAGE = 'REMOVE_IMAGES_FROM_LOCAL_STORAGE';

export const KEY = {
    API: {
        IMAGES: 'images'
    },
    LOCAL_FORAGE: {
        BULK_UPLOAD_BAKERY: 'bulkUploadBakery'
    }
};
