export const STUFF = 'STUFF';

export const ADMIN_BULK_UPLOAD_REQUEST = 'ADMIN_BULK_UPLOAD_REQUEST';
export const ADMIN_BULK_UPLOAD_SUCCESS = 'ADMIN_BULK_UPLOAD_SUCCESS';
export const ADMIN_BULK_UPLOAD_FAILURE = 'ADMIN_BULK_UPLOAD_FAILURE';

export const ADMIN_BULK_UDATE_BAKERY_REQUEST = 'ADMIN_BULK_UDATE_BAKERY_REQUEST';
export const ADMIN_BULK_UDATE_BAKERY_SUCCESS = 'ADMIN_BULK_UDATE_BAKERY_SUCCESS';
export const ADMIN_BULK_UDATE_BAKERY_FAILURE = 'ADMIN_BULK_UDATE_BAKERY_FAILURE';

export const ADMIN_CREATE_NEW_BASIS_REQUEST = 'ADMIN_CREATE_NEW_BASIS_REQUEST';
export const ADMIN_CREATE_NEW_BASIS_SUCCESS = 'ADMIN_CREATE_NEW_BASIS_SUCCESS';
export const ADMIN_CREATE_NEW_BASIS_FAILURE = 'ADMIN_CREATE_NEW_BASIS_FAILURE';

export const ADMIN_CREATE_NEW_FILLING_REQUEST = 'ADMIN_CREATE_NEW_FILLING_REQUEST';
export const ADMIN_CREATE_NEW_FILLING_SUCCESS = 'ADMIN_CREATE_NEW_FILLING_SUCCESS';
export const ADMIN_CREATE_NEW_FILLING_FAILURE = 'ADMIN_CREATE_NEW_FILLING_FAILURE';

export const ADMIN_CREATE_NEW_INGREDIENT_REQUEST = 'ADMIN_CREATE_NEW_INGREDIENT_REQUEST';
export const ADMIN_CREATE_NEW_INGREDIENT_SUCCESS = 'ADMIN_CREATE_NEW_INGREDIENT_SUCCESS';
export const ADMIN_CREATE_NEW_INGREDIENT_FAILURE = 'ADMIN_CREATE_NEW_INGREDIENT_FAILURE';

export const ADMIN_CREATE_NEW_EVENT_REQUEST = 'ADMIN_CREATE_NEW_EVENT_REQUEST';
export const ADMIN_CREATE_NEW_EVENT_SUCCESS = 'ADMIN_CREATE_NEW_EVENT_SUCCESS';
export const ADMIN_CREATE_NEW_EVENT_FAILURE = 'ADMIN_CREATE_NEW_EVENT_FAILURE';

export const ADMIN_CREATE_NEW_DECOR = 'ADMIN_CREATE_NEW_DECOR';

export const ADMIN_GET_INGREDIENTS_REQUEST = 'ADMIN_GET_INGREDIENTS_REQUEST';
export const ADMIN_GET_INGREDIENTS_SUCCESS = 'ADMIN_GET_INGREDIENTS_SUCCESS';
export const ADMIN_GET_INGREDIENTS_FAILURE = 'ADMIN_GET_INGREDIENTS_FAILURE';

export const ADMIN_GET_FILLING_REQUEST = 'ADMIN_GET_FILLING_REQUEST';
export const ADMIN_GET_FILLING_SUCCESS = 'ADMIN_GET_FILLING_SUCCESS';
export const ADMIN_GET_FILLING_FAILURE = 'ADMIN_GET_FILLING_FAILURE';

export const ADMIN_GET_BASIS_REQUEST = 'ADMIN_GET_BASIS_REQUEST';
export const ADMIN_GET_BASIS_SUCCESS = 'ADMIN_GET_BASIS_SUCCESS';
export const ADMIN_GET_BASIS_FAILURE = 'ADMIN_GET_BASIS_FAILURE';

export const ADMIN_GET_EVENTS_REQUEST = 'ADMIN_GET_EVENTS_REQUEST';
export const ADMIN_GET_EVENTS_SUCCESS = 'ADMIN_GET_EVENTS_SUCCESS';
export const ADMIN_GET_EVENTS_FAILURE = 'ADMIN_GET_EVENTS_FAILURE';

export const ADMIN_GET_BAKERY_ITEM_REQUEST = 'ADMIN_GET_BAKERY_ITEM_REQUEST';
export const ADMIN_GET_BAKERY_ITEM_SUCCESS = 'ADMIN_GET_BAKERY_ITEM_SUCCESS';
export const ADMIN_GET_BAKERY_ITEM_FAILURE = 'ADMIN_GET_BAKERY_ITEM_FAILURE';

export const ADMIN_GET_INQUIRY_REQUEST = 'ADMIN_GET_INQUIRY_REQUEST';
export const ADMIN_GET_INQUIRY_SUCCESS = 'ADMIN_GET_INQUIRY_SUCCESS';
export const ADMIN_GET_INQUIRY_FAILURE = 'ADMIN_GET_INQUIRY_FAILURE';

export const ADMIN_RESOLVE_INQUIRY_REQUEST = 'ADMIN_RESOLVE_INQUIRY_REQUEST';
export const ADMIN_RESOLVE_INQUIRY_SUCCESS = 'ADMIN_RESOLVE_INQUIRY_SUCCESS';
export const ADMIN_RESOLVE_INQUIRY_FAILURE = 'ADMIN_RESOLVE_INQUIRY_FAILURE';

export const ADMIN_UPDATE_PRICE_INQUIRY_REQUEST = 'ADMIN_UPDATE_PRICE_INQUIRY_REQUEST';
export const ADMIN_UPDATE_PRICE_INQUIRY_SUCCESS = 'ADMIN_UPDATE_PRICE_INQUIRY_SUCCESS';
export const ADMIN_UPDATE_PRICE_INQUIRY_FAILURE = 'ADMIN_UPDATE_PRICE_INQUIRY_FAILURE';

export const IMAGES_FROM_LOCAL_STORAGE = 'IMAGES_FROM_LOCAL_STORAGE';
export const IMAGES_TO_LOCAL_STORAGE = 'IMAGES_TO_LOCAL_STORAGE';
export const SET_CURRENT_FILE_TO_CROP = 'SET_CURRENT_FILE_TO_CROP';
export const REMOVE_IMAGES_FROM_LOCAL_STORAGE = 'REMOVE_IMAGES_FROM_LOCAL_STORAGE';

export const SET_CURRENT_INGREDIENTS = 'SET_CURRENT_INGREDIENTS';
export const SET_CURRENT_FILLING = 'SET_CURRENT_FILLING';
export const SET_CURRENT_BASIS = 'SET_CURRENT_BASIS';
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT';

export const SHOW_INGREDIENTS_NEW_FORM = 'SHOW_INGREDIENTS_NEW_FORM';
export const SHOW_FILLING_NEW_FORM = 'SHOW_FILLING_NEW_FORM';
export const SHOW_BASIS_NEW_FORM = 'SHOW_BASIS_NEW_FORM';
export const SHOW_EVENT_NEW_FORM = 'SHOW_EVENT_NEW_FORM';
export const HIDE_ALL_FORMS = 'HIDE_ALL_FORMS';

export const SET_CURRENT_INGREDIENT_FOR_CREATION_FORM = 'SET_CURRENT_INGREDIENT_FOR_CREATION_FORM';
export const SET_CURRENT_FILLING_FOR_CREATION_FORM = 'SET_CURRENT_FILLING_FOR_CREATION_FORM';
export const SET_CURRENT_BASIS_FOR_CREATION_FORM = 'SET_CURRENT_BASIS_FOR_CREATION_FORM';

export const CLEAR_CURRENT_STUFF = 'CLEAR_CURRENT_STUFF';
export const SET_CURRENT_STUFF = 'SET_CURRENT_STUFF';

export const KEY = {
    API: {
        IMAGES: 'images'
    },
    LOCAL_FORAGE: {
        BULK_UPLOAD_BAKERY: 'bulkUploadBakery'
    }
};
