export const BAKERY_GET_ALL_REQUEST = 'BAKERY_GET_ALL_REQUEST';
export const BAKERY_GET_ALL_SUCCESS = 'BAKERY_GET_ALL_SUCCESS';
export const BAKERY_GET_ALL_FAILURE = 'BAKERY_GET_ALL_FAILURE';

export const BAKERY_COUNT_REQUEST = 'BAKERY_COUNT_REQUEST';
export const BAKERY_COUNT_SUCCESS = 'BAKERY_COUNT_SUCCESS';
export const BAKERY_COUNT_FAILURE = 'BAKERY_COUNT_FAILURE';

export const BAKERY_ADD_MORE_REQUEST = 'BAKERY_ADD_MORE_REQUEST';
export const BAKERY_ADD_MORE_SUCCESS = 'BAKERY_ADD_MORE_SUCCESS';
export const BAKERY_ADD_MORE_FAILURE = 'BAKERY_ADD_MORE_FAILURE';

export const SET_CURRENT_SKIP = 'SET_CURRENT_SKIP';
