export const CART_INQUIRY_GET_REQUEST = 'CART_INQUIRY_GET_REQUEST';
export const CART_INQUIRY_GET_SUCCESS = 'CART_INQUIRY_GET_SUCCESS';
export const CART_INQUIRY_GET_FAILURE = 'CART_INQUIRY_GET_FAILURE';

export const CART_SET_CART_REDIRECT_ID= 'CART_SET_CART_REDIRECT_ID';
export const CART_REMOVE_CART_REDIRECT_ID= 'CART_REMOVE_CART_REDIRECT_ID';

export const CURRENT_INQUIRY_ID= 'CURRENT_INQUIRY_ID';
